language: go

go:
  - 1.15

script:
  - make

after_success:
  - docker build -t meowfaceman/script-on-docker-events .

deploy:
  provider: script
  script: bash scripts/dockerhub_push.sh
  on:
    branch: master
