events:
  - id: test event 1
    type: container
    action: start
    commands:
      - echo "1"
      - ""
  - id: test event 2
    type: container
    action: die
    commands:
      - echo "3"
      - echo "4"